---
- name: install apache
  hosts: Slave1
  become: yes
  tasks:
    - name: run apt-get update
      apt:
       update_cache: yes
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start service
      systemd:
        name: apache2
        state: restarted
    - name: replace default apache page with custom html file
      copy: src=/etc/ansible/gitCode/index.html dest=/var/www/html/
