---
- name: install nginx
  hosts: all
  become: yes
  tasks:
    - name: run apt-get update
      apt:
       update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: start service
      systemd:
        name: nginx
        state: restarted
    - name: replace default nginx page with custom html file
      copy: src=/etc/ansible/gitCode/index.html dest=/var/www/html/
